[build]
    command = "npm run build"
    publish = ".next"

[dev]
    command = "npm run dev"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[[redirects]]
    from = "/app/*"
    to = "/app/index.html"
    status = 200